
app = 'rgou1'
primary_region = 'lhr'

[build]

[env]
PORT = '9223'

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = ["app"]

[[services]]
protocol = 'tcp'
internal_port = 8080

[[services.ports]]
port = 80
handlers = ['http']

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
